---
apiVersion: v1
kind: Secret
metadata:
  name: my-dsp-abc-rhoai-sklearn-dsp-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/stefan-bergstein/my-dsp-abc-rhoai-sklearn-gitops
