app:
  name: my-dsp-abc-rhoai-sklearn-dsp
  namespace: my-dsp-abc
  cluster: .apps.ocp5.stormshift.coe.muc.redhat.com
  user: admin

git:
  branch: main
  repo: https://github.com/stefan-bergstein/my-dsp-abc-rhoai-sklearn
